# Generated by Django 2.2.4 on 2019-08-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_path', models.TextField(db_index=True)),
                ('height', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='branches.Branch')),
                ('root', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_nodes', to='branches.Branch')),
            ],
        ),
    ]
