# Generated by Django 2.2.4 on 2019-08-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='node_path',
            new_name='up_path',
        ),
    ]
