# Generated by Django 2.2.4 on 2019-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20190803_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.BigIntegerField()),
                ('height', models.BigIntegerField(default=0)),
                ('parent', models.BigIntegerField(default=None, null=True)),
                ('root', models.BigIntegerField(default=None, null=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['node_id'], name='branches_of_node_id_7efa94_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['node_id', 'height'], name='branches_of_node_id_342306_idx'),
        ),
    ]
