# Generated by Django 2.2.4 on 2019-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20190804_1408'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='office',
            name='branches_of_node_id_7efa94_idx',
        ),
        migrations.AlterField(
            model_name='office',
            name='node_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
