# Generated by Django 2.2.4 on 2019-08-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_auto_20190804_1537'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='office',
            name='branches_of_node_id_342306_idx',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='node_id',
            new_name='node_pos',
        ),
        migrations.AlterField(
            model_name='office',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_children', to='branches.Office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='root',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_nodes', to='branches.Office'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['node_pos', 'height'], name='branches_of_node_po_ea4f5a_idx'),
        ),
    ]
