# Generated by Django 2.2.4 on 2019-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_auto_20190804_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='node_pos',
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['node_pos'], name='branches_of_node_po_5d3338_idx'),
        ),
    ]
