# Generated by Django 2.2.4 on 2019-08-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_auto_20190804_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='node_pos',
            field=models.BigIntegerField(default=0),
        ),
    ]
