# Generated by Django 2.2.4 on 2019-08-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_auto_20190804_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='root',
        ),
        migrations.RemoveIndex(
            model_name='office',
            name='branches_of_node_po_ea4f5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='office',
            name='branches_of_node_po_5d3338_idx',
        ),
        migrations.AddField(
            model_name='office',
            name='next_pos',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='node_pos',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='office',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_children', to='branches.Office'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
