# Generated by Django 2.2.4 on 2019-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_auto_20190805_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='node_pos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['node_pos'], name='branches_of_node_po_5d3338_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['node_pos', 'desc_count'], name='branches_of_node_po_8da749_idx'),
        ),
    ]
